Associate `dragging-layer` to `tabGroup`.
ticlo/rc-dock pull request #181
Opened 2022-12-02 23:14 UTC by Shravankumarkarnati

Adds the `dock-panel` classes to the `dragging-layer` too. 

Currently, we don't have a way to link the `dragging layer` to its `drag element`. We have multiple panels with different groups and styles. It is not possible for us to style the elements in dragging layers and to align their styles to their parent panels or tabs.

2022-12-03 01:27 UTC, slavamuravey requested changes

2022-12-03 01:27 UTC, slavamuravey commented on src/dragdrop/DragManager.ts
> +  _draggingDiv.className = classNames;
The code can be shorter:
```
const tabGroup = _data['tabGroup'] as string | undefined;

_draggingDiv.className = (tabGroup?.split(" ").map(name => `dock-style-${name}`) ?? []).concat("dragging-layer").join(" ");
```

2022-12-03 18:17 UTC, Shravankumarkarnati commented on src/dragdrop/DragManager.ts
> +  _draggingDiv.className = classNames;
Updated!

2022-12-04 04:27 UTC, slavamuravey approved these changes

2022-12-20 08:05 UTC, merged